version: '3.8'

services:
  zdd_api:
    build:
      context: .
      dockerfile: ./dockers/api/Dockerfile
    restart: unless-stopped
    # command: yarn dev
    command: node src/index.js
    ports:
      - 3000
    networks:
      - zdd
    volumes:
      - ./:/app

  nginx:
    image: nginx:1.21.6
    container_name: zdd_nginx
    restart: always
    volumes:
      - ./dockers/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    networks:
      - zdd
    depends_on:
      - zdd_api

networks:
  zdd:
    driver: bridge
